# Generated by Django 5.1.1 on 2024-09-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('plat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='plat.plat')),
            ],
        ),
    ]
